<a href="https://colab.research.google.com/github/alejandraconb-dev/SupplyChainLogysticsData/blob/main/SupplyChainLogysticsData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("omarstat2/supply-chain-logistics-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'supply-chain-logistics-data' dataset.
Path to dataset files: /kaggle/input/supply-chain-logistics-data

In [8]:
import os

# Ver qué archivos hay
print("\nArchivos descargados:")
for f in os.listdir(path):
    print(f" - {f}")

Archivos descargados:
 - ProductsPerPlant.csv
 - VmiCustomers.csv
 - FreightRates.csv
 - PlantPorts.csv
 - OrderList.csv
 - WhCosts.csv
 - WhCapacities.csv

In [9]:
import os
import pandas as pd

# Construir la ruta al archivo ProductsPerPlant.csv usando la variable path existente
file_path = os.path.join(path, "ProductsPerPlant.csv")

# Cargar el archivo CSV en un DataFrame
df_products = pd.read_csv(file_path)

# Mostrar las primeras filas
display(df_products.head())

  Plant Code  Product ID
0    PLANT15     1698815
1    PLANT17     1664419
2    PLANT17     1664426
3    PLANT17     1672826
4    PLANT17     1674916

In [10]:
import os
import pandas as pd

# Construir la ruta al archivo VmiCustomers.csv
file_path_vmi = os.path.join(path, "VmiCustomers.csv")

# Cargar el archivo CSV en un DataFrame
df_vmi_customers = pd.read_csv(file_path_vmi)

# Mostrar las primeras filas
display(df_vmi_customers.head())

  Plant Code            Customers
0    PLANT02    V5555555555555_16
1    PLANT02  V555555555555555_29
2    PLANT02         V555555555_3
3    PLANT02    V55555555555555_8
4    PLANT02          V55555555_9

In [11]:
import os
import pandas as pd

# Construir la ruta al archivo FreightRates.csv
file_path_freight = os.path.join(path, "FreightRates.csv")

# Cargar el archivo CSV en un DataFrame
df_freight_rates = pd.read_csv(file_path_freight)

# Mostrar las primeras filas
display(df_freight_rates.head())

,Carrier,orig_port_cd,dest_port_cd,minm_wgh_qty,max_wgh_qty,svc_cd,minimum cost,rate,mode_dsc,tpt_day_cnt,Carrier type
0,V444_6,PORT08,PORT09,250.0,499.99,DTD,43.2272,0.7132,AIR,2,V88888888_0
1,V444_6,PORT08,PORT09,65.0,69.99,DTD,43.2272,0.7512,AIR,2,V88888888_0
2,V444_6,PORT08,PORT09,60.0,64.99,DTD,43.2272,0.7892,AIR,2,V88888888_0
3,V444_6,PORT08,PORT09,50.0,54.99,DTD,43.2272,0.8272,AIR,2,V88888888_0
4,V444_6,PORT08,PORT09,35.0,39.99,DTD,43.2272,1.0552,AIR,2,V88888888_0

In [12]:
import os
import pandas as pd

# Construir la ruta al archivo PlantPorts.csv usando la variable path existente
file_path = os.path.join(path, "PlantPorts.csv")

# Cargar el archivo CSV en un DataFrame
df_products = pd.read_csv(file_path)

# Mostrar las primeras filas
display(df_products.head())

  Plant Code    Port
0    PLANT01  PORT01
1    PLANT01  PORT02
2    PLANT02  PORT03
3    PLANT03  PORT04
4    PLANT04  PORT05

In [13]:
import os
import pandas as pd

# Construir la ruta al archivo OrderList.csv usando la variable path existente
file_path = os.path.join(path, "OrderList.csv")

# Cargar el archivo CSV en un DataFrame
df_products = pd.read_csv(file_path)

# Mostrar las primeras filas
display(df_products.head())

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code,Destination Port,Unit quantity,Weight
0,1.447296e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1.447158e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1.447139e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [14]:
import os
import pandas as pd

# Construir la ruta al archivo WhCosts.csv usando la variable path existente
file_path = os.path.join(path, "WhCosts.csv")

# Cargar el archivo CSV en un DataFrame
df_products = pd.read_csv(file_path)

# Mostrar las primeras filas
display(df_products.head())

        WH  Cost/unit
0  PLANT15   1.415063
1  PLANT17   0.428947
2  PLANT18   2.036254
3  PLANT05   0.488144
4  PLANT02   0.477504

In [16]:
import os
import pandas as pd

# Construir la ruta al archivo WhCapacities.csv usando la variable path existente
file_path = os.path.join(path, "WhCapacities.csv")

# Cargar el archivo CSV en un DataFrame
df_products = pd.read_csv(file_path)

# Mostrar las primeras filas
display(df_products.head())

  Plant ID  Daily Capacity
0  PLANT15               11
1  PLANT17                8
2  PLANT18              111
3  PLANT05              385
4  PLANT02              138